window:
  name: "SURGE Default Window"
  monitor_index: 1
  windowed: true
  cursor: true
  resolution:
    width: 800
    height: 600
  VSync:
    enabled: true
renderer:
  clear_color:
    r: 0.2
    g: 0.3
    b: 0.3
    a: 1.0
modules: ["model_viewer"]
