window:
  name: "SURGE: Demo Triangle Module"
  monitor_index: 1
  windowed: true
  cursor: true

resolution:
  width: 800
  height: 600

renderer:
  VSync: true
  MSAA: true
  fps_cap: true # Ignored on Windows
  fps_cap_value: 60


clear_color:
  r: 0.2
  g: 0.3
  b: 0.3
  a: 1.0

modules:
  first_module: "triangle"
