window:
  name: "SURGE: Default Module"
  monitor_index: 1
  windowed: 1
  cursor: 1

resolution:
  width: 800
  height: 600

renderer:
  VSync: 1
  MSAA: 1

clear_color:
  r: 0.0
  g: 0.0
  b: 0.0
  a: 1.0

modules:
  first_module: "default"