window:
  name: "SURGE 2048"
  monitor_index: 1
  windowed: true
  cursor: true
  resolution:
    width: 454
    height: 454
  VSync:
    enabled: true
renderer:
  clear_color:
    r: 0.2
    g: 0.3
    b: 0.3
    a: 1.0
modules: ["2048"]
