window:
  name: "SURGE 2048"
  monitor_index: 1
  windowed: true
  cursor: true
  resolution:
    width: 500
    height: 800
  VSync:
    enabled: true
renderer:
  clear_color:
    r: 0.980
    g: 0.973
    b: 0.937
    a: 1.0
modules: ["2048"]
